baseURL = 'https://blog.kitepon.dev/'
languageCode = 'ja'
defaultContentLanguage = 'ja'
hasCJKLanguage = true
title = 'Claude Code 始めました'
timeZone = 'Asia/Tokyo'

[params]
  description = 'Claude MAXユーザーが、実際の開発で使いながら掴んだことを記録していくシリーズ。「使ってるけど実は知らなかった」層に向けた、現場の記録。'
  author = 'クオ'
  twitter = 'QLyun35332'
  mainSections = ['post']

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[[menus.main]]
  name = 'About'
  url = '/about/'
  weight = 10

[pagination]
  pagerSize = 100
