baseURL = 'https://kitepon-rgb.github.io/WebAICoding/'
languageCode = 'ja'
defaultContentLanguage = 'ja'
title = 'Claude Code 始めました'
theme = 'paper'

[params]
  description = 'Claude MAXユーザーの実体験ベース技術ブログ'
  twitter = 'qlyun35332'

[markup]
  [markup.highlight]
    style = 'github'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menus.main]]
  name = 'About'
  url = '/about/'
  weight = 10

[pagination]
  pagerSize = 10
